Gigasecond
amymhaddad/test_driven_development pull request #6
Opened 2019-09-28 11:59 UTC by amymhaddad

@paulghaddad Please review this program and its tests. I have one question about a test that I wrote:

`assert gigasecond(datetime.now()) == datetime.now() + seconds`

I get an error when I run the above line, and I'm not clear why?

2019-10-09 23:35 UTC, paulghaddad commented on gigasecond/test_gigasecond.py
> +# def test_todays_date():
I wouldn't even test this...this is one of the hardest things to test.  The two `.now()` calls will be separated by a millisecond and will always fail. To get this test to work, you'd have to do:

````
current_time = datetime.now() # assures this current time is exactly the same
assert gigasecond(current_time == current_time + seconds
```

2019-10-09 23:35 UTC, paulghaddad commented on gigasecond/test_gigasecond.py
> +    assert gigasecond(datetime(2020, 4, 11)) == datetime(2020, 4, 11) + seconds
You can extract `datetime(2020, 4, 11)` as a named variable, otherwise it's duplication.

2019-10-09 23:36 UTC, paulghaddad requested changes
Nice work! Two small comments to consider.

2019-10-11 14:55 UTC, amymhaddad commented
@paulghaddad Ready for final review. Here are my changes:
1. Updated this test:
```
def test_todays_date():
    current_time = datetime.now()
    assert gigasecond(current_time) == current_time + seconds
```
2. Used `birthdate `variable for all tests to reduce duplication of datetime object.

2019-10-28 22:13 UTC, paulghaddad approved these changes
Approved! Nice job!

2019-10-28 22:13 UTC, paulghaddad commented on gigasecond/test_gigasecond.py
> +seconds = timedelta(seconds=1000000000)
Nice job making this a constant. You could even make it all upcase.

2019-10-28 22:14 UTC, paulghaddad commented on gigasecond/test_gigasecond.py
> +def test_recent_date_time():
Nice clean tests with correct style.

2019-10-31 21:42 UTC, merged